language: go
go:
  - 1.9
cache:
  directories:
    - vendor
    - $HOME/.glide
before_install:
  # Install Glide
  - curl https://glide.sh/get | bash
install:
  - glide install -v
before_script:
  - go get -u golang.org/x/tools/cmd/cover
script: go test -v -cover -bench=. ./...
